"""adjusted equipment tables

Revision ID: 015417bfbbd7
Revises: d7df3583127f
Create Date: 2022-04-25 19:06:19.991802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015417bfbbd7'
down_revision = 'd7df3583127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_class', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('refrigerant_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('heating_equipment')
    op.drop_table('packaged_equipment')
    op.drop_table('air_handling_equipment')
    op.drop_table('cooling_equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('serial_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('equipment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('refrigerant_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='cooling_equipment_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cooling_equipment_pkey')
    )
    op.create_table('air_handling_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('serial_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('equipment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='air_handling_equipment_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='air_handling_equipment_pkey')
    )
    op.create_table('packaged_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipment_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('serial_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('equipment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('refrigerant_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='packaged_equipment_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='packaged_equipment_pkey')
    )
    op.create_table('heating_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('serial_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('equipment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='heating_equipment_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='heating_equipment_pkey')
    )
    op.drop_table('equipment')
    # ### end Alembic commands ###
