"""adjusted adresses

Revision ID: 317ba88e39cb
Revises: 
Create Date: 2022-04-13 19:36:20.868116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317ba88e39cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.drop_column('company', 'street_address_1')
    op.drop_column('company', 'street_address_2')
    op.add_column('customer', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.drop_column('customer', 'street_address_1')
    op.drop_column('customer', 'street_address_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('street_address_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('street_address_1', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('customer', 'street_address')
    op.add_column('company', sa.Column('street_address_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('street_address_1', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('company', 'street_address')
    # ### end Alembic commands ###
