"""added customer id to work order

Revision ID: 411e183c5adc
Revises: eec42143666c
Create Date: 2022-04-26 19:40:53.833489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411e183c5adc'
down_revision = 'eec42143666c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_order', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_order', type_='foreignkey')
    op.drop_column('work_order', 'customer_id')
    # ### end Alembic commands ###
