"""added work orders

Revision ID: 45b149b8b74a
Revises: 015417bfbbd7
Create Date: 2022-04-26 17:56:43.721668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45b149b8b74a'
down_revision = '015417bfbbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('work_performed', sa.String(length=1000), nullable=False),
    sa.Column('order_type', sa.String(length=25), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('repair_log')
    op.drop_table('maintenance_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_performed', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='maintenance_log_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenance_log_pkey')
    )
    op.create_table('repair_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_performed', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name='repair_log_system_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repair_log_pkey')
    )
    op.drop_table('work_order')
    # ### end Alembic commands ###
