"""added relationships:

Revision ID: 8e2e597f2410
Revises: 411e183c5adc
Create Date: 2022-04-26 20:06:10.118104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2e597f2410'
down_revision = '411e183c5adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_order', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_order', type_='foreignkey')
    op.drop_column('work_order', 'customer_id')
    # ### end Alembic commands ###
