"""added functionality

Revision ID: d7df3583127f
Revises: 3d7af72023a8
Create Date: 2022-04-25 18:53:11.571974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7df3583127f'
down_revision = '3d7af72023a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaged_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_class', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('refrigerant_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packaged_equipment')
    # ### end Alembic commands ###
