"""adjusted work order table

Revision ID: eec42143666c
Revises: 45b149b8b74a
Create Date: 2022-04-26 19:11:24.033256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec42143666c'
down_revision = '45b149b8b74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_order', type_='foreignkey')
    op.drop_column('work_order', 'user_id')
    # ### end Alembic commands ###
